// Groups
export const ADD_GROUP = 'ADD_GROUP'
export const EDIT_GROUP = 'EDIT_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'

// Items
export const REQUEST_ITEMS = 'REQUEST_ITEMS'
export const RECEIVE_ITEMS_SUCCESS = 'RECEIVE_ITEMS_SUCCESS'
export const RECEIVE_ITEMS_FAIL = 'RECEIVE_ITEMS_FAIL'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'
export const ADD_ITEM = 'ADD_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'

// User
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'

// Other
export const UPDATE_CURRENCY_SYMBOL = 'UPDATE_CURRENCY_SYMBOL'
