// Items
export const REQUEST_ITEMS = 'REQUEST_ITEMS'
export const RECEIVE_ITEMS_SUCCESS = 'RECEIVE_ITEMS_SUCCESS'
export const RECEIVE_ITEMS_FAIL = 'RECEIVE_ITEMS_FAIL'
export const ADD_ITEM = 'ADD_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'

// User
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
